package com.baoshen.cameralib.pb;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/PbCameraParameter.proto

public final class PbCameraParameterOuterClass {
  private PbCameraParameterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PbCameraParameterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PbCameraParameter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *是否成功
     * </pre>
     *
     * <code>required bool IsSuccess = 1;</code>
     */
    boolean hasIsSuccess();
    /**
     * <pre>
     *是否成功
     * </pre>
     *
     * <code>required bool IsSuccess = 1;</code>
     */
    boolean getIsSuccess();

    /**
     * <pre>
     *异常信息
     * </pre>
     *
     * <code>optional string ErrorMessage = 2;</code>
     */
    boolean hasErrorMessage();
    /**
     * <pre>
     *异常信息
     * </pre>
     *
     * <code>optional string ErrorMessage = 2;</code>
     */
    String getErrorMessage();
    /**
     * <pre>
     *异常信息
     * </pre>
     *
     * <code>optional string ErrorMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();

    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    java.util.List<PbKeyValueOuterClass.PbKeyValue> 
        getParametersList();
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    PbKeyValueOuterClass.PbKeyValue getParameters(int index);
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    int getParametersCount();
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    java.util.List<? extends PbKeyValueOuterClass.PbKeyValueOrBuilder> 
        getParametersOrBuilderList();
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    PbKeyValueOuterClass.PbKeyValueOrBuilder getParametersOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code PbCameraParameter}
   */
  public  static final class PbCameraParameter extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PbCameraParameter)
      PbCameraParameterOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PbCameraParameter.newBuilder() to construct.
    private PbCameraParameter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PbCameraParameter() {
      isSuccess_ = false;
      errorMessage_ = "";
      parameters_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PbCameraParameter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              isSuccess_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorMessage_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                parameters_ = new java.util.ArrayList<PbKeyValueOuterClass.PbKeyValue>();
                mutable_bitField0_ |= 0x00000004;
              }
              parameters_.add(
                  input.readMessage(PbKeyValueOuterClass.PbKeyValue.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          parameters_ = java.util.Collections.unmodifiableList(parameters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PbCameraParameterOuterClass.internal_static_PbCameraParameter_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PbCameraParameterOuterClass.internal_static_PbCameraParameter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PbCameraParameter.class, Builder.class);
    }

    private int bitField0_;
    public static final int ISSUCCESS_FIELD_NUMBER = 1;
    private boolean isSuccess_;
    /**
     * <pre>
     *是否成功
     * </pre>
     *
     * <code>required bool IsSuccess = 1;</code>
     */
    public boolean hasIsSuccess() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *是否成功
     * </pre>
     *
     * <code>required bool IsSuccess = 1;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private volatile Object errorMessage_;
    /**
     * <pre>
     *异常信息
     * </pre>
     *
     * <code>optional string ErrorMessage = 2;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *异常信息
     * </pre>
     *
     * <code>optional string ErrorMessage = 2;</code>
     */
    public String getErrorMessage() {
      Object ref = errorMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *异常信息
     * </pre>
     *
     * <code>optional string ErrorMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMETERS_FIELD_NUMBER = 3;
    private java.util.List<PbKeyValueOuterClass.PbKeyValue> parameters_;
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    public java.util.List<PbKeyValueOuterClass.PbKeyValue> getParametersList() {
      return parameters_;
    }
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    public java.util.List<? extends PbKeyValueOuterClass.PbKeyValueOrBuilder> 
        getParametersOrBuilderList() {
      return parameters_;
    }
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    public int getParametersCount() {
      return parameters_.size();
    }
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    public PbKeyValueOuterClass.PbKeyValue getParameters(int index) {
      return parameters_.get(index);
    }
    /**
     * <pre>
     *相机参数
     * </pre>
     *
     * <code>repeated .PbKeyValue Parameters = 3;</code>
     */
    public PbKeyValueOuterClass.PbKeyValueOrBuilder getParametersOrBuilder(
        int index) {
      return parameters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIsSuccess()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getParametersCount(); i++) {
        if (!getParameters(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
      }
      for (int i = 0; i < parameters_.size(); i++) {
        output.writeMessage(3, parameters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuccess_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
      }
      for (int i = 0; i < parameters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, parameters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PbCameraParameter)) {
        return super.equals(obj);
      }
      PbCameraParameter other = (PbCameraParameter) obj;

      boolean result = true;
      result = result && (hasIsSuccess() == other.hasIsSuccess());
      if (hasIsSuccess()) {
        result = result && (getIsSuccess()
            == other.getIsSuccess());
      }
      result = result && (hasErrorMessage() == other.hasErrorMessage());
      if (hasErrorMessage()) {
        result = result && getErrorMessage()
            .equals(other.getErrorMessage());
      }
      result = result && getParametersList()
          .equals(other.getParametersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIsSuccess()) {
        hash = (37 * hash) + ISSUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsSuccess());
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      if (getParametersCount() > 0) {
        hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getParametersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PbCameraParameter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PbCameraParameter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PbCameraParameter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PbCameraParameter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PbCameraParameter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PbCameraParameter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PbCameraParameter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PbCameraParameter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PbCameraParameter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PbCameraParameter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PbCameraParameter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PbCameraParameter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PbCameraParameter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PbCameraParameter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PbCameraParameter)
        PbCameraParameterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PbCameraParameterOuterClass.internal_static_PbCameraParameter_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PbCameraParameterOuterClass.internal_static_PbCameraParameter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PbCameraParameter.class, Builder.class);
      }

      // Construct using PbCameraParameterOuterClass.PbCameraParameter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParametersFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        isSuccess_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (parametersBuilder_ == null) {
          parameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          parametersBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PbCameraParameterOuterClass.internal_static_PbCameraParameter_descriptor;
      }

      @Override
      public PbCameraParameter getDefaultInstanceForType() {
        return PbCameraParameter.getDefaultInstance();
      }

      @Override
      public PbCameraParameter build() {
        PbCameraParameter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PbCameraParameter buildPartial() {
        PbCameraParameter result = new PbCameraParameter(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSuccess_ = isSuccess_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMessage_ = errorMessage_;
        if (parametersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            parameters_ = java.util.Collections.unmodifiableList(parameters_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.parameters_ = parameters_;
        } else {
          result.parameters_ = parametersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PbCameraParameter) {
          return mergeFrom((PbCameraParameter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PbCameraParameter other) {
        if (other == PbCameraParameter.getDefaultInstance()) return this;
        if (other.hasIsSuccess()) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000002;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        if (parametersBuilder_ == null) {
          if (!other.parameters_.isEmpty()) {
            if (parameters_.isEmpty()) {
              parameters_ = other.parameters_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureParametersIsMutable();
              parameters_.addAll(other.parameters_);
            }
            onChanged();
          }
        } else {
          if (!other.parameters_.isEmpty()) {
            if (parametersBuilder_.isEmpty()) {
              parametersBuilder_.dispose();
              parametersBuilder_ = null;
              parameters_ = other.parameters_;
              bitField0_ = (bitField0_ & ~0x00000004);
              parametersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParametersFieldBuilder() : null;
            } else {
              parametersBuilder_.addAllMessages(other.parameters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasIsSuccess()) {
          return false;
        }
        for (int i = 0; i < getParametersCount(); i++) {
          if (!getParameters(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PbCameraParameter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PbCameraParameter) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean isSuccess_ ;
      /**
       * <pre>
       *是否成功
       * </pre>
       *
       * <code>required bool IsSuccess = 1;</code>
       */
      public boolean hasIsSuccess() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *是否成功
       * </pre>
       *
       * <code>required bool IsSuccess = 1;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <pre>
       *是否成功
       * </pre>
       *
       * <code>required bool IsSuccess = 1;</code>
       */
      public Builder setIsSuccess(boolean value) {
        bitField0_ |= 0x00000001;
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否成功
       * </pre>
       *
       * <code>required bool IsSuccess = 1;</code>
       */
      public Builder clearIsSuccess() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuccess_ = false;
        onChanged();
        return this;
      }

      private Object errorMessage_ = "";
      /**
       * <pre>
       *异常信息
       * </pre>
       *
       * <code>optional string ErrorMessage = 2;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *异常信息
       * </pre>
       *
       * <code>optional string ErrorMessage = 2;</code>
       */
      public String getErrorMessage() {
        Object ref = errorMessage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *异常信息
       * </pre>
       *
       * <code>optional string ErrorMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *异常信息
       * </pre>
       *
       * <code>optional string ErrorMessage = 2;</code>
       */
      public Builder setErrorMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *异常信息
       * </pre>
       *
       * <code>optional string ErrorMessage = 2;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *异常信息
       * </pre>
       *
       * <code>optional string ErrorMessage = 2;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
        return this;
      }

      private java.util.List<PbKeyValueOuterClass.PbKeyValue> parameters_ =
        java.util.Collections.emptyList();
      private void ensureParametersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          parameters_ = new java.util.ArrayList<PbKeyValueOuterClass.PbKeyValue>(parameters_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PbKeyValueOuterClass.PbKeyValue, PbKeyValueOuterClass.PbKeyValue.Builder, PbKeyValueOuterClass.PbKeyValueOrBuilder> parametersBuilder_;

      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public java.util.List<PbKeyValueOuterClass.PbKeyValue> getParametersList() {
        if (parametersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(parameters_);
        } else {
          return parametersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public int getParametersCount() {
        if (parametersBuilder_ == null) {
          return parameters_.size();
        } else {
          return parametersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public PbKeyValueOuterClass.PbKeyValue getParameters(int index) {
        if (parametersBuilder_ == null) {
          return parameters_.get(index);
        } else {
          return parametersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder setParameters(
          int index, PbKeyValueOuterClass.PbKeyValue value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.set(index, value);
          onChanged();
        } else {
          parametersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder setParameters(
          int index, PbKeyValueOuterClass.PbKeyValue.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.set(index, builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder addParameters(PbKeyValueOuterClass.PbKeyValue value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.add(value);
          onChanged();
        } else {
          parametersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder addParameters(
          int index, PbKeyValueOuterClass.PbKeyValue value) {
        if (parametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParametersIsMutable();
          parameters_.add(index, value);
          onChanged();
        } else {
          parametersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder addParameters(
          PbKeyValueOuterClass.PbKeyValue.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.add(builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder addParameters(
          int index, PbKeyValueOuterClass.PbKeyValue.Builder builderForValue) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.add(index, builderForValue.build());
          onChanged();
        } else {
          parametersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder addAllParameters(
          Iterable<? extends PbKeyValueOuterClass.PbKeyValue> values) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, parameters_);
          onChanged();
        } else {
          parametersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder clearParameters() {
        if (parametersBuilder_ == null) {
          parameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          parametersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public Builder removeParameters(int index) {
        if (parametersBuilder_ == null) {
          ensureParametersIsMutable();
          parameters_.remove(index);
          onChanged();
        } else {
          parametersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public PbKeyValueOuterClass.PbKeyValue.Builder getParametersBuilder(
          int index) {
        return getParametersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public PbKeyValueOuterClass.PbKeyValueOrBuilder getParametersOrBuilder(
          int index) {
        if (parametersBuilder_ == null) {
          return parameters_.get(index);  } else {
          return parametersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public java.util.List<? extends PbKeyValueOuterClass.PbKeyValueOrBuilder> 
           getParametersOrBuilderList() {
        if (parametersBuilder_ != null) {
          return parametersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(parameters_);
        }
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public PbKeyValueOuterClass.PbKeyValue.Builder addParametersBuilder() {
        return getParametersFieldBuilder().addBuilder(
            PbKeyValueOuterClass.PbKeyValue.getDefaultInstance());
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public PbKeyValueOuterClass.PbKeyValue.Builder addParametersBuilder(
          int index) {
        return getParametersFieldBuilder().addBuilder(
            index, PbKeyValueOuterClass.PbKeyValue.getDefaultInstance());
      }
      /**
       * <pre>
       *相机参数
       * </pre>
       *
       * <code>repeated .PbKeyValue Parameters = 3;</code>
       */
      public java.util.List<PbKeyValueOuterClass.PbKeyValue.Builder> 
           getParametersBuilderList() {
        return getParametersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PbKeyValueOuterClass.PbKeyValue, PbKeyValueOuterClass.PbKeyValue.Builder, PbKeyValueOuterClass.PbKeyValueOrBuilder> 
          getParametersFieldBuilder() {
        if (parametersBuilder_ == null) {
          parametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PbKeyValueOuterClass.PbKeyValue, PbKeyValueOuterClass.PbKeyValue.Builder, PbKeyValueOuterClass.PbKeyValueOrBuilder>(
                  parameters_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          parameters_ = null;
        }
        return parametersBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PbCameraParameter)
    }

    // @@protoc_insertion_point(class_scope:PbCameraParameter)
    private static final PbCameraParameter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PbCameraParameter();
    }

    public static PbCameraParameter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<PbCameraParameter>
        PARSER = new com.google.protobuf.AbstractParser<PbCameraParameter>() {
      @Override
      public PbCameraParameter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PbCameraParameter(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PbCameraParameter> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PbCameraParameter> getParserForType() {
      return PARSER;
    }

    @Override
    public PbCameraParameter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PbCameraParameter_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PbCameraParameter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036protos/PbCameraParameter.proto\032\027protos" +
      "/PbKeyValue.proto\"]\n\021PbCameraParameter\022\021" +
      "\n\tIsSuccess\030\001 \002(\010\022\024\n\014ErrorMessage\030\002 \001(\t\022" +
      "\037\n\nParameters\030\003 \003(\0132\013.PbKeyValue"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PbKeyValueOuterClass.getDescriptor(),
        }, assigner);
    internal_static_PbCameraParameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PbCameraParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PbCameraParameter_descriptor,
        new String[] { "IsSuccess", "ErrorMessage", "Parameters", });
    PbKeyValueOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
